CREATE TABLE [dbo].[EDL_HANA_FCT_SALES_LINE_FEES] (

	[PK_HASH_SK] varchar(40) NOT NULL, 
	[DATE_SK] bigint NULL, 
	[BRANCH_SK] bigint NULL, 
	[CUSTOMER_SK] bigint NULL, 
	[SUPPLIER_SK] bigint NULL, 
	[PRODUCT_SK] bigint NULL, 
	[INVOICE_NUM] varchar(10) NULL, 
	[INVOICE_LINE_NUM] decimal(5,0) NULL, 
	[INVOICE_TYPE] varchar(3) NULL, 
	[CREDIT_ORD_FLG] varchar(1) NULL, 
	[ORG_CL_ORD] varchar(3) NULL, 
	[TYPE_OF_DATA] varchar(15) NULL, 
	[FEES_CD] varchar(10) NULL, 
	[FEES_TYPE] varchar(5) NULL, 
	[FEES_DESC] varchar(25) NULL, 
	[FEES_LONG_DESC] varchar(50) NULL, 
	[DIST_FEE_INCL] varchar(1) NULL, 
	[ALLOWANCE_TYPE] varchar(3) NULL, 
	[ADD_SUB_FLG] varchar(1) NULL, 
	[CATCH_WGHT_CD] varchar(1) NULL, 
	[FEES_AMOUNT] float NULL, 
	[RFEE_CD] varchar(5) NULL, 
	[RFEE_DESC] varchar(25) NULL, 
	[RFEE_PER_UNIT] float NULL, 
	[ITM_PRICE_BEF_DFEE] float NULL, 
	[DFEE_EXT_GST_TAX] float NULL, 
	[INTER_BRANCH_CD] varchar(1) NULL, 
	[INTERNAL_SALES_IND] varchar(8) NULL, 
	[ITEM_TYPE_CD] varchar(10) NULL, 
	[BAN_GRP_CD] varchar(10) NULL, 
	[ACCOUNT_NUM] varchar(8) NULL, 
	[CLAIM_IND] varchar(1) NULL, 
	[YEAR_MONTH] int NULL, 
	[EXTRACT_DAY_NUM] int NULL, 
	[CREATED_BATCH_NO] decimal(10,0) NULL, 
	[UPDATED_BATCH_NO] decimal(10,0) NULL, 
	[CREATED_DT] datetime2(3) NULL, 
	[UPDATED_DT] datetime2(3) NULL, 
	[CREATED_BY] varchar(50) NULL, 
	[UPDATED_BY] varchar(50) NULL, 
	[SOURCE_SYSTEM_CD] int NULL, 
	[HDR_FEE_IND] varchar(1) NULL, 
	[BRANCH_NUM] varchar(8) NULL, 
	[CUSTOMER_CD] varchar(13) NULL, 
	[FISC_YEAR] int NOT NULL
);