CREATE TABLE [dbo].[EDL_HANA_DIM_PRODUCT_MANAGER] (

	[PRODUCT_MANAGER_SK] float NOT NULL, 
	[PRODUCT_MANAGER_GROUP_CD] varchar(16) NULL, 
	[PRODUCT_MANAGER_CD] varchar(16) NULL, 
	[PRODUCT_MANAGER_NM] varchar(80) NULL, 
	[HEAD_OF_MERCHANDISE_CD] varchar(16) NULL, 
	[HEAD_OF_MERCHANDISE_NM] varchar(80) NULL, 
	[GENERAL_MANAGER_CD] varchar(16) NULL, 
	[GENERAL_MANAGER_NM] varchar(80) NULL, 
	[MANAGER_TYP] varchar(2) NULL, 
	[EXTRACT_DAY_NUM] float NULL, 
	[CREATED_BATCH_NO] float NULL, 
	[UPDATED_BATCH_NO] float NULL, 
	[CREATED_DT] datetime2(3) NULL, 
	[UPLOADED_DT] datetime2(3) NULL, 
	[CREATED_BY] varchar(100) NULL, 
	[UPLOADED_BY] varchar(100) NULL
);