CREATE TABLE [dbo].[EDL_hana_fct_allowance_type] (

	[PK_HASH_SK] varchar(32) NOT NULL, 
	[DATE_SK] bigint NOT NULL, 
	[BRANCH_SK] bigint NOT NULL, 
	[CUSTOMER_SK] bigint NOT NULL, 
	[SUPPLIER_SK] bigint NOT NULL, 
	[PRODUCT_SK] bigint NOT NULL, 
	[INVOICE_NUM] varchar(22) NULL, 
	[INVOICE_PAGE_NUM] varchar(10) NULL, 
	[INVOICE_LINE_NUM] varchar(10) NULL, 
	[LINE_SEQUENCE_NUM] decimal(10,0) NULL, 
	[ORDER_NUM] varchar(10) NULL, 
	[INTER_BRANCH_TYP] varchar(15) NULL, 
	[ALLOWANCE_CD] varchar(8) NULL, 
	[ALLOWANCE_DSC] varchar(100) NULL, 
	[ALLOWANCE_TYPE] varchar(8) NULL, 
	[CUSTOMER_ALLOWANCE_XMT] float NULL, 
	[VENDOR_ALLOWANCE_XMT] float NULL, 
	[CLAIM_IND] varchar(1) NULL, 
	[BRANCH_NUM] varchar(8) NULL, 
	[CUSTOMER_CD] varchar(10) NULL, 
	[SUPPLIER_CD] varchar(10) NULL, 
	[PRODUCT_CD] varchar(10) NULL, 
	[INTERNAL_SALES_IND] varchar(8) NULL, 
	[SOURCE_SYSTEM_CD] varchar(8) NULL, 
	[EXTRACT_DAY_NUM] decimal(10,0) NULL, 
	[CREATED_BY] varchar(100) NULL, 
	[CREATED_DT] datetime2(3) NULL, 
	[CREATED_BATCH_NO] decimal(10,0) NULL
);