CREATE TABLE [dbo].[EDL_HANA_DIM_BRANCH] (

	[BRANCH_SK] bigint NOT NULL, 
	[BRANCH_NUM] varchar(15) NULL, 
	[BRANCH_LONG_NM] varchar(255) NULL, 
	[BRANCH_SHORT_NM] varchar(255) NULL, 
	[MN_COMPANY_CD] varchar(8) NULL, 
	[COUNTRY_CD] varchar(8) NULL, 
	[COMPANY_CD] varchar(8) NULL, 
	[BUS_PILLAR_CD] varchar(8) NULL, 
	[PILLAR_STATE_CD] varchar(8) NULL, 
	[MN_COMP_NM] varchar(40) NULL, 
	[COUNTRY_NM] varchar(40) NULL, 
	[COUNTRY_FORMAL_NM] varchar(40) NULL, 
	[COMP_NM] varchar(40) NULL, 
	[BUS_PILLAR_NM] varchar(40) NULL, 
	[PILLAR_STATE_NUM] varchar(8) NULL, 
	[PILLAR_STATE_NM] varchar(40) NULL, 
	[DIVISION_CD] varchar(8) NULL, 
	[DIVISION_NM] varchar(40) NULL, 
	[PRIM_ST_LINE] varchar(256) NULL, 
	[PRIM_LOCY_NM] varchar(64) NULL, 
	[PRIM_POST_CD] varchar(32) NULL, 
	[PRIM_PHONE_NUM] varchar(20) NULL, 
	[PRIM_FAX_NUM] varchar(20) NULL, 
	[SECOND_ST_LINE] varchar(256) NULL, 
	[SECOND_LOCY_NM] varchar(64) NULL, 
	[SECOND_POST_CD] varchar(32) NULL, 
	[SECOND_PHONE_NUM] varchar(20) NULL, 
	[BOND_REGO_NUM] varchar(8) NULL, 
	[LIQ_LIC_NUM] varchar(15) NULL, 
	[TRADE_STAT_CD] varchar(8) NULL, 
	[GROCERY_GOODS_IND] varchar(1) NULL, 
	[PERISH_GOODS_IND] varchar(1) NULL, 
	[LIQ_GOODS_IND] varchar(1) NULL, 
	[TBCO_GOODS_IND] varchar(1) NULL, 
	[FRESH_GOODS_IND] varchar(1) NULL, 
	[GEN_MRCH_GOODS_IND] varchar(1) NULL, 
	[ON_LINE_POS_IND] varchar(1) NULL, 
	[TBCO_LIC_NUM] varchar(15) NULL, 
	[CCC_REG_ZONE_CD] varchar(8) NULL, 
	[CCC_WS_DISC_IND] varchar(1) NULL, 
	[CCC_PRICE_ZONE_CD] varchar(8) NULL, 
	[INV_BRCH_NUM] varchar(8) NULL, 
	[WAREHOUSE_BRANCH_CD] varchar(8) NULL, 
	[DISTRIBUTION_CENTRE_CD] varchar(8) NULL, 
	[WAREHOUSE_CD] varchar(8) NULL, 
	[MAIN_ADDRESS_COUNTRY_TXT] varchar(64) NULL, 
	[SECOND_ADDRESS_COUNTRY_TXT] varchar(64) NULL, 
	[MAIN_ADDRESS_STATE_TXT] varchar(32) NULL, 
	[SECOND_ADDRESS_STATE_TXT] varchar(32) NULL, 
	[BUSINESS_UNIT_NUM] varchar(40) NULL, 
	[EFF_START_DT] datetime2(3) NOT NULL, 
	[EFF_END_DT] datetime2(3) NOT NULL, 
	[ACTIVE_FLAG] varchar(1) NULL, 
	[CREATED_BATCH_NO] decimal(10,0) NULL, 
	[UPDATED_BATCH_NO] decimal(10,0) NULL, 
	[CREATED_DT] datetime2(3) NULL, 
	[UPDATED_DT] datetime2(3) NULL, 
	[CREATED_BY] varchar(40) NULL, 
	[UPDATED_BY] varchar(40) NULL, 
	[SOURCE_SYSTEM_CD] int NULL, 
	[UPSERT_FLAG] decimal(10,0) NULL, 
	[CONV_BRANCH_NUM] varchar(15) NULL, 
	[CHAMBER_NM] varchar(100) NULL
);