CREATE TABLE [dbo].[FOOD_DW_DIM_FOOD_PRODUCT_CATEGORY_V] (

	[SOURCE] varchar(10) NULL, 
	[CP_KEY_CATEGORY] varchar(50) NULL, 
	[CP_KEY_MANAGER] varchar(50) NULL, 
	[CP_KEY_PDM] varchar(50) NULL, 
	[CP_KEY_PDM_MANAGER] varchar(50) NULL, 
	[BUSINESS_PILLAR] varchar(10) NULL, 
	[MSC_CATEGORY_CODE] varchar(8) NULL, 
	[MSC_CATEGORY_NAME] varchar(40) NULL, 
	[MSC_COMMODITY_CODE] varchar(8) NULL, 
	[MSC_COMMODITY_NAME] varchar(40) NULL, 
	[MSC_SUB_COMMODITY_CODE] varchar(8) NULL, 
	[MSC_SUB_COMMODITY_NAME] varchar(40) NULL, 
	[MSC_SECTION_CODE] varchar(8) NULL, 
	[MSC_SECTION_NAME] varchar(40) NULL, 
	[MSC_DEPT_CODE] varchar(8) NULL, 
	[MSC_DEPT_NAME] varchar(40) NULL, 
	[CATEGORY_MANAGER_CODE] varchar(10) NULL, 
	[PDM_MANAGER_CODE] varchar(10) NULL, 
	[SEGMENT_HOT] varchar(20) NULL, 
	[SEGMENT_TM] varchar(30) NULL
);