name: "Protect main branch"
rules:
  - type: branch
    pattern: main
    allow_force_pushes: false
    allow_deletions: false
    required_approving_review_count: 1
    required_status_checks:
      - "build"
      - "test"
    require_linear_history: true
    require_signed_commits: true
    restrict_pushes: true
    restrict_push_users: [] # Empty means only admins can push (optional)
    restrict_review_dismissals: true
    restrict_review_dismissal_users: []
    required_conversation_resolution: true
    required_pull_request_reviews: true
    require_code_owner_reviews: false
    block_creations: false
    enforce_admins: true
    dismiss_stale_reviews: true
    require_commit_signatures: true
    bypass_push_restrictions: false
