storage:
  - lakehouse: local
    lh_bronze: lh_bronze
    lh_silver: lh_silver
    lh_gold: lh_gold

  - warehouses: local
    wh_reporting: wh_reporting

  - sqldatabases: local
    db_config: db_config
