# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "jupyter",
# META     "jupyter_kernel_name": "python3.11"
# META   },
# META   "dependencies": {}
# META }

# MARKDOWN ********************

# ## dbtload_lakehouse: dbt build `path:models`
#
# A Python notebook (no Spark session of its own) that runs dbt against the project uploaded to
# the config lakehouse (`ingen_fab deploy upload-dbt-project --dbt-project dbt_project`),
# with the adapter the project's `requirements.txt` names. Where the models execute depends on
# that adapter: dbt-fabricspark opens a Spark (Livy) session on the profile's lakehouse,
# dbt-fabric runs T-SQL in the warehouse. A Fabric token is fetched in this notebook and passed
# to dbt as DBT_FABRIC_TOKEN for profiles that use it.
# The profile target is `<environment>-notebook`, generated by `ingen_fab dbt profile`.
#
# Every step runs through Python with a failure check, so a failed install or a failed dbt run
# fails the notebook job. dbt writes its `target/` and logs to local scratch space.
# The run is logged by dbt's on-run-end hook (`macros/ingen_fab_logging.sql`): one row in
# `dbt_batch` and one per model and test in `dbt_execution_log`, in the log lakehouse
# (`lh_log`) for a dbt-fabricspark project or the log warehouse for a dbt-fabric
# one; a store the workspace lacks falls back to the project's own lakehouse or warehouse.
# On failure only,
# the step logs, dbt's own log files and the notebook's error are kept under
# `Files/dbt_failures/dbt_project/dbtload_lakehouse/<timestamp>/` of the log lakehouse.

# CELL ********************

# MAGIC %%configure
# MAGIC {
# MAGIC     "defaultLakehouse": {
# MAGIC         "name": "config"
# MAGIC     }
# MAGIC }

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "jupyter_python"
# META }

# PARAMETERS CELL ********************

dbt_command = "build"
dbt_select = "path:models"
dbt_threads = 4
dbt_vars = "{silver_lakehouse: lh_silver_nb, gold_lakehouse: lh_gold_nb}"
dbt_target = ""  # empty: <environment>-notebook
dbt_indirect_selection = ""  # empty: dbt's default and the project's flags

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "jupyter_python"
# META }

# CELL ********************

import json
import os
import subprocess
import sys
import time
import traceback
import uuid
from datetime import datetime, timezone
from pathlib import Path

ALLOWED = set(["build", "compile", "run", "seed", "snapshot", "test"])
if dbt_command not in ALLOWED:
    raise ValueError(f"Invalid dbt_command {dbt_command!r}. Allowed: {sorted(ALLOWED)}")

# Names rendered as JSON strings and joined as path parts: a quote or backslash in a project,
# notebook or lakehouse name cannot break this code
DBT_PROJECT = "dbt_project"
NOTEBOOK_NAME = "dbtload_lakehouse"
LOG_LAKEHOUSE = "lh_log"
LOG_WAREHOUSE = ""  # empty: the project's own `log_warehouse` var, else wh_log
PROJECT_DIR = Path("/lakehouse/default/Files") / DBT_PROJECT
# one folder per run: the UTC stamp orders them, the short id keeps two runs that start in
# the same second apart
STAMP = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ") + "_" + uuid.uuid4().hex[:8]
LOCAL_RUN = Path("/tmp/dbt_runs") / NOTEBOOK_NAME / STAMP
LOCAL_RUN.mkdir(parents=True, exist_ok=True)
STARTED = time.time()
STEPS = []
# Environment variables for the dbt process, each read from the Variable Library at run time
# (for example a warehouse SQL endpoint that the profile reads with env_var()).
ENV_FROM_VARIABLES = {}


def variable(name):
    """A value of the Variable Library deployed with this workspace."""
    return notebookutils.variableLibrary.get(f"$(/**/var_lib/{name})")  # noqa: F821


# The run's record is written by dbt itself: the on-run-end hook (macros/ingen_fab_logging.sql,
# maintained by ingen_fab) appends one row to dbt_batch and one row per model and test to
# dbt_execution_log in the log store (the log lakehouse for a dbt-fabricspark project, the log
# warehouse for a dbt-fabric project, or the project's own storage when that store does not
# exist). This notebook writes no log of its own; on a failure it keeps the step logs, dbt's
# own log files and the error in the log lakehouse so the cause is at hand.
FAILURE_FOLDER = (
    f"abfss://{variable(LOG_LAKEHOUSE + '_workspace_id')}@onelake.dfs.fabric.microsoft.com/"
    f"{variable(LOG_LAKEHOUSE + '_lakehouse_id')}/Files/dbt_failures/{DBT_PROJECT}/{NOTEBOOK_NAME}/{STAMP}"
)


def keep_failure(error):
    """The step logs (pip_install.log, dbt_<command>.log), dbt's own log and the notebook's
    error to the log lakehouse, for a failed run only."""
    kept = 0
    for path in [*sorted(LOCAL_RUN.glob("*.log")), *sorted((LOCAL_RUN / "dbt_logs").glob("*.log"))]:
        if not path.is_file():
            continue
        try:
            notebookutils.fs.put(f"{FAILURE_FOLDER}/{path.name}", path.read_text(encoding="utf-8", errors="replace"), True)  # noqa: F821
            kept += 1
        except Exception as e:  # one unreadable file must not hide the run's real outcome
            print(f"could not keep {path.name}: {type(e).__name__}: {e}")
    print(f"failed: {error}; {kept} file(s) kept under {FAILURE_FOLDER}")


def print_summary(status):
    print(json.dumps({
        "notebook": NOTEBOOK_NAME,
        "dbt_project": DBT_PROJECT,
        "command": dbt_command,
        "select": dbt_select,
        "target": dbt_target,
        "status": status,
        "started_utc": STAMP,
        "seconds": round(time.time() - STARTED, 1),
        "steps": STEPS,
    }, indent=2))


def step(name, command, env=None):
    """Run a command, write its output to <name>.log, fail the notebook on a non-zero exit."""
    log = LOCAL_RUN / f"{name}.log"
    began = time.time()
    with log.open("w", encoding="utf-8") as f:
        proc = subprocess.run(command, cwd=str(PROJECT_DIR), env=env, stdout=f, stderr=subprocess.STDOUT, text=True)
    STEPS.append({"step": name, "exit": proc.returncode, "seconds": round(time.time() - began, 1)})
    tail = log.read_text(encoding="utf-8", errors="replace").splitlines()[-40:]
    print(f"--- {name}: exit {proc.returncode}")
    print("\n".join(tail))
    if proc.returncode != 0:
        raise RuntimeError(f"{name} failed with exit code {proc.returncode}; see {name}.log under {FAILURE_FOLDER}")


try:
    # The environment comes from the Variable Library, so the same notebook selects the right
    # profile target in development, test and production.
    environment = variable("fabric_environment")
    target = dbt_target or f"{environment}-notebook"
    # The token is fetched here and handed to the dbt child process: the profile's notebook
    # target reads it from DBT_FABRIC_TOKEN (notebookutils is not available in a child process).
    fabric_token = notebookutils.credentials.getToken("pbi")  # noqa: F821

    step("pip_install", [sys.executable, "-m", "pip", "install", "-q", "-r", str(PROJECT_DIR / "requirements.txt")])

    dbt_exe = Path(sys.executable).parent / "dbt"
    dbt = [str(dbt_exe)] if dbt_exe.is_file() else [sys.executable, "-m", "dbt.cli.main"]
    env = {
        **os.environ,
        "DBT_PROJECT_DIR": str(PROJECT_DIR),
        "DBT_PROFILES_DIR": str(PROJECT_DIR / "profiles"),
        "DBT_TARGET_PATH": str(LOCAL_RUN / "target"),
        "DBT_LOG_PATH": str(LOCAL_RUN / "dbt_logs"),
        "DBT_USE_COLORS": "false",
        "DBT_FABRIC_TOKEN": fabric_token,
        "PYTHONUNBUFFERED": "1",
        "PATH": f"{Path(sys.executable).parent}{os.pathsep}{os.environ.get('PATH', '')}",
        **{name: variable(source) for name, source in ENV_FROM_VARIABLES.items()},
    }
    arguments = [dbt_command, "--select", dbt_select, "--target", target, "--threads", str(dbt_threads)]
    if dbt_indirect_selection:
        arguments += ["--indirect-selection", dbt_indirect_selection]
    # dbt vars: the caller's, plus what the logging macro needs (the log store, who ran dbt);
    # a value the caller gave wins
    import yaml  # installed with dbt
    run_vars = dict(yaml.safe_load(dbt_vars) or {}) if dbt_vars else {}
    run_vars.setdefault("log_lakehouse", LOG_LAKEHOUSE)
    if LOG_WAREHOUSE:
        run_vars.setdefault("log_warehouse", LOG_WAREHOUSE)
    run_vars["ingen_fab_runner"] = "notebook/" + NOTEBOOK_NAME
    arguments += ["--vars", json.dumps(run_vars)]
    # Packages are not part of the upload: a project that declares them gets `dbt deps` first,
    # installed into this run's scratch folder so the uploaded project stays untouched
    if any((PROJECT_DIR / name).is_file() for name in ("packages.yml", "dependencies.yml")):
        env["DBT_PACKAGES_INSTALL_PATH"] = str(LOCAL_RUN / "dbt_packages")
        step("dbt_deps", dbt + ["deps"], env=env)
    print("dbt " + " ".join(arguments))
    step("dbt_" + dbt_command, dbt + arguments, env=env)
except BaseException as e:
    (LOCAL_RUN / "notebook_error.log").write_text(traceback.format_exc(), encoding="utf-8")
    print_summary("failed")
    keep_failure(f"{type(e).__name__}: {e}")
    raise
else:
    print_summary("succeeded")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "jupyter_python"
# META }