{#
  Generated by ingen_fab (`ingen_fab dbt profile`, `ingen_fab dbt <verb>`, `ingen_fab dbt
  orchestrator` refresh it): do not edit, it is overwritten.

  Run logging into the log store, by dbt itself, from an on-run-end hook:

      on-run-end:
        - "{{ ingen_fab_log_run(results) }}"

  Two tables, the ones the Spark adapter's projects have always had:
    dbt_batch          one row per dbt invocation (batch_id = invocation_id)
    dbt_execution_log  one row per model, test, seed and snapshot of that invocation

  Where they live:
    dbt-fabricspark (lakehouse projects): the log lakehouse, var `log_lakehouse` (lh_log)
    dbt-fabric (warehouse projects):      the log warehouse, var `log_warehouse` (wh_log),
                                          schema var `log_schema` (dbo)
  The orchestrator notebook passes both vars; from a machine, set them with --vars or in
  dbt_project.yml. `ingen_fab_runner` names who ran dbt (cli, or notebook/<name>).
#}

{% macro ingen_fab_log_run(results) %}
    {% if execute and results | length > 0 %}
        {% if target.type == 'fabricspark' %}
            {{ ingen_fab_log_run_spark(results) }}
        {% elif target.type == 'fabric' %}
            {{ ingen_fab_log_run_warehouse(results) }}
        {% else %}
            {{ log("ingen_fab logging: no log store for adapter " ~ target.type ~ "; run not logged", info=True) }}
        {% endif %}
    {% endif %}
{% endmacro %}


{# ---------------------------------------------------------------------------------------- #}
{# the rows, adapter-neutral                                                                   #}

{% macro ingen_fab_sql_string(value, max_length=4000) %}
    {%- if value is none -%}NULL{%- else -%}'{{ (value | string)[:max_length] | replace("'", "''") }}'{%- endif -%}
{% endmacro %}

{% macro ingen_fab_timestamp(value, sql_type) %}
    {%- if value is none -%}NULL{%- else -%}CAST('{{ value.strftime('%Y-%m-%d %H:%M:%S') }}' AS {{ sql_type }}){%- endif -%}
{% endmacro %}

{% macro ingen_fab_node_rows(results) %}
    {%- set rows = [] -%}
    {%- for result in results -%}
        {#- a Jinja `set` inside a loop stays in the loop: the namespace carries the timing out -#}
        {%- set ns = namespace(started=none, ended=none) -%}
        {%- for t in result.timing -%}
            {%- if t.name == 'execute' or (t.name == 'compile' and ns.started is none) -%}
                {%- set ns.started = t.started_at -%}
                {%- set ns.ended = t.completed_at -%}
            {%- endif -%}
        {%- endfor -%}
        {%- do rows.append({
            'unique_id': result.node.unique_id,
            'resource_type': result.node.resource_type,
            'name': result.node.name,
            'status': result.status | string,
            'message': result.message,
            'execution_time': result.execution_time or 0,
            'started_at': ns.started,
            'ended_at': ns.ended,
            'failures': result.failures or 0,
        }) -%}
    {%- endfor -%}
    {{ return(rows) }}
{% endmacro %}

{% macro ingen_fab_batch_row(results) %}
    {%- set statuses = results | map(attribute='status') | map('string') | list -%}
    {%- set selector = invocation_args_dict.get('select') if invocation_args_dict is defined else none -%}
    {%- if selector is iterable and selector is not string -%}{%- set selector = selector | join(' ') -%}{%- endif -%}
    {%- set errors = statuses | select('in', ['error', 'fail']) | list | length -%}
    {{ return({
        'batch_id': invocation_id,
        'project_name': project_name,
        'target_name': target.name,
        'target_type': target.type,
        'command': flags.WHICH,
        'selector': selector,
        'runner': var('ingen_fab_runner', 'cli'),
        'started_at': run_started_at,
        'ended_at': modules.datetime.datetime.utcnow(),
        'status': 'error' if errors > 0 else 'success',
        'total_nodes': statuses | length,
        'success_count': statuses | select('in', ['success', 'pass']) | list | length,
        'error_count': statuses | select('equalto', 'error') | list | length,
        'fail_count': statuses | select('equalto', 'fail') | list | length,
        'skipped_count': statuses | select('equalto', 'skipped') | list | length,
        'warn_count': statuses | select('equalto', 'warn') | list | length,
    }) }}
{% endmacro %}

{% macro ingen_fab_node_values(rows, batch_id, ts_type) %}
    {%- for r in rows -%}
        ({{ ingen_fab_sql_string(batch_id) }}, {{ ingen_fab_sql_string(r.unique_id) }}, {{ ingen_fab_sql_string(r.resource_type) }}, {{ ingen_fab_sql_string(r.name) }}, {{ ingen_fab_sql_string(r.status) }}, {{ ingen_fab_sql_string(r.message) }}, {{ r.execution_time }}, {{ ingen_fab_timestamp(r.started_at, ts_type) }}, {{ ingen_fab_timestamp(r.ended_at, ts_type) }}, {{ r.failures }}){{ ", " if not loop.last }}
    {%- endfor -%}
{% endmacro %}

{% macro ingen_fab_batch_values(b, ts_type) %}
    ({{ ingen_fab_sql_string(b.batch_id) }}, {{ ingen_fab_sql_string(b.project_name) }}, {{ ingen_fab_sql_string(b.target_name) }}, {{ ingen_fab_sql_string(b.target_type) }}, {{ ingen_fab_sql_string(b.command) }}, {{ ingen_fab_sql_string(b.selector) }}, {{ ingen_fab_sql_string(b.runner) }}, {{ ingen_fab_timestamp(b.started_at, ts_type) }}, {{ ingen_fab_timestamp(b.ended_at, ts_type) }}, {{ ingen_fab_sql_string(b.status) }}, {{ b.total_nodes }}, {{ b.success_count }}, {{ b.error_count }}, {{ b.fail_count }}, {{ b.skipped_count }}, {{ b.warn_count }})
{% endmacro %}


{# ---------------------------------------------------------------------------------------- #}
{# dbt-fabricspark: Delta tables in the log lakehouse                                         #}

{% macro ingen_fab_log_run_spark(results) %}
    {%- set db = var('log_lakehouse', 'lh_log') -%}
    {%- set batch = db ~ '.dbt_batch' -%}
    {%- set log_table = db ~ '.dbt_execution_log' -%}
    {% do run_query("CREATE TABLE IF NOT EXISTS " ~ batch ~ " (batch_id STRING, project_name STRING, target_name STRING, target_type STRING, command STRING, selector STRING, runner STRING, started_at TIMESTAMP, ended_at TIMESTAMP, status STRING, total_nodes INT, success_count INT, error_count INT, fail_count INT, skipped_count INT, warn_count INT) USING DELTA") %}
    {% do run_query("CREATE TABLE IF NOT EXISTS " ~ log_table ~ " (batch_id STRING, unique_id STRING, resource_type STRING, name STRING, status STRING, message STRING, execution_time DOUBLE, started_at TIMESTAMP, ended_at TIMESTAMP, failures INT) USING DELTA") %}
    {%- set rows = ingen_fab_node_rows(results) -%}
    {%- set b = ingen_fab_batch_row(results) -%}
    {%- for chunk in rows | batch(200) -%}
        {% do run_query("INSERT INTO " ~ log_table ~ " VALUES " ~ ingen_fab_node_values(chunk, b.batch_id, 'TIMESTAMP')) %}
    {%- endfor -%}
    {% do run_query("INSERT INTO " ~ batch ~ " VALUES " ~ ingen_fab_batch_values(b, 'TIMESTAMP')) %}
    {{ log("ingen_fab logging: " ~ rows | length ~ " node row(s) and the batch row written to " ~ db, info=True) }}
{% endmacro %}


{# ---------------------------------------------------------------------------------------- #}
{# dbt-fabric: tables in the log warehouse                                                    #}

{% macro ingen_fab_log_run_warehouse(results) %}
    {%- set db = var('log_warehouse', 'wh_log') -%}
    {%- set schema = var('log_schema', 'dbo') -%}
    {%- set batch = db ~ '.' ~ schema ~ '.dbt_batch' -%}
    {%- set log_table = db ~ '.' ~ schema ~ '.dbt_execution_log' -%}
    {% do run_query("IF OBJECT_ID('" ~ batch ~ "') IS NULL CREATE TABLE " ~ batch ~ " (batch_id VARCHAR(64), project_name VARCHAR(256), target_name VARCHAR(256), target_type VARCHAR(64), command VARCHAR(64), selector VARCHAR(4000), runner VARCHAR(256), started_at DATETIME2(3), ended_at DATETIME2(3), status VARCHAR(32), total_nodes INT, success_count INT, error_count INT, fail_count INT, skipped_count INT, warn_count INT)") %}
    {% do run_query("IF OBJECT_ID('" ~ log_table ~ "') IS NULL CREATE TABLE " ~ log_table ~ " (batch_id VARCHAR(64), unique_id VARCHAR(1024), resource_type VARCHAR(64), name VARCHAR(512), status VARCHAR(32), message VARCHAR(4000), execution_time FLOAT, started_at DATETIME2(3), ended_at DATETIME2(3), failures INT)") %}
    {%- set rows = ingen_fab_node_rows(results) -%}
    {%- set b = ingen_fab_batch_row(results) -%}
    {%- for chunk in rows | batch(200) -%}
        {% do run_query("INSERT INTO " ~ log_table ~ " VALUES " ~ ingen_fab_node_values(chunk, b.batch_id, 'DATETIME2(3)')) %}
    {%- endfor -%}
    {% do run_query("INSERT INTO " ~ batch ~ " VALUES " ~ ingen_fab_batch_values(b, 'DATETIME2(3)')) %}
    {{ log("ingen_fab logging: " ~ rows | length ~ " node row(s) and the batch row written to " ~ db ~ "." ~ schema, info=True) }}
{% endmacro %}
