name: "Feature Request"
description: "Suggest an idea or enhancement."
title: "[FEATURE] <short description>"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature!
  - type: input
    id: summary
    attributes:
      label: "Short summary of the feature"
      description: "A concise description of the feature or enhancement."
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Why is this feature important? What problem does it solve?"
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: "Proposed solution"
      description: "Describe the solution you'd like."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives considered"
      description: "Have you considered any alternatives?"
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here."
    validations:
      required: false
