CREATE TABLE [dbo].[BKP_FCT_FOOD_SALES_FEES_DAILY_V_CAB_20240911] (

	[DATE_SK] bigint NULL, 
	[FISCALWEEKENDDATE] bigint NULL, 
	[BRANCH_SK] bigint NULL, 
	[BRANCH_NUM] varchar(15) NULL, 
	[CUSTOMER_SK] bigint NULL, 
	[CUSTOMER_CD] varchar(13) NULL, 
	[SUPPLIER_SK] bigint NULL, 
	[SA_CD] varchar(10) NULL, 
	[SUPPLIER_CD] varchar(10) NULL, 
	[PRODUCT_SK] bigint NULL, 
	[PRODUCT_CD] varchar(60) NULL, 
	[MSC_CATEGORY_CD] varchar(8) NULL, 
	[INVOICE_NUM] varchar(10) NULL, 
	[INVOICE_LINE_NUM] decimal(5,0) NULL, 
	[INVOICE_TYPE] varchar(3) NULL, 
	[FEES_CD] varchar(10) NULL, 
	[FEE_CD_DESC] varchar(25) NULL, 
	[FEES_TYPE] varchar(5) NULL, 
	[DIST_FEE_INCL] varchar(1) NULL, 
	[ALLOWANCE_TYPE] varchar(3) NULL, 
	[RFEE_CD] varchar(5) NULL, 
	[RFEE_DESC] varchar(25) NULL, 
	[RFEE_PER_UNIT] float NULL, 
	[INTERNAL_SALES_IND] varchar(8) NULL, 
	[CLAIM_IND] varchar(1) NULL, 
	[SOURCE_SYSTEM_CD] int NULL, 
	[HDR_FEE_IND] varchar(1) NULL, 
	[PrivateLabel_Flag] varchar(11) NOT NULL, 
	[FEE_PLACEMENT_DSC] varchar(21) NOT NULL, 
	[FEES_AMOUNT] float NULL, 
	[ACCOUNT_NUM] varchar(8) NULL, 
	[Realligned_Tobacco_Flag] varchar(2) NOT NULL, 
	[CP_KEY_CATEGORY] varchar(41) NOT NULL, 
	[CP_KEY_PDM] varchar(41) NOT NULL
);