CREATE TABLE [dbo].[FOOD_DW_FCT_FOOD_SALES_ALLOWANCE_DAILY_V] (

	[branch_sk] bigint NOT NULL, 
	[branch_num] varchar(15) NULL, 
	[customer_sk] bigint NOT NULL, 
	[customer_cd] varchar(13) NULL, 
	[date_sk] bigint NOT NULL, 
	[FISCALWEEKENDDATE] bigint NULL, 
	[product_sk] bigint NOT NULL, 
	[product_cd] varchar(60) NULL, 
	[msc_category_cd] varchar(8) NULL, 
	[supplier_sk] bigint NOT NULL, 
	[supplier_cd] varchar(10) NULL, 
	[sa_cd] varchar(10) NULL, 
	[source_system_cd] varchar(8) NULL, 
	[internal_sales_ind] varchar(8) NULL, 
	[allowance_cd] varchar(8) NULL, 
	[ALLOWANCE_TYPE] varchar(8) NULL, 
	[ALLOWANCE_DSC] varchar(100) NULL, 
	[PrivateLabel_Flag] varchar(11) NOT NULL, 
	[VENDOR_FUNDED_ALLOWANCE_XMT] float NULL, 
	[VENDOR_FUNDED_ITEM_ALLOWANCE_XMT] float NULL, 
	[METCASH_FUNDED_ALLOWANCE_XMT] float NULL, 
	[METCASH_FUNDED_ITEM_ALLOWANCE_XMT] float NULL, 
	[METCASH_UNMAPPED_CUSTOMER_ALLOWANCE] float NULL, 
	[METCASH_UNMAPPED_SUPPLIER_ALLOWANCE] float NULL, 
	[CUSTOMER_ALLOWANCE_XMT] float NULL, 
	[VENDOR_ALLOWANCE_XMT] float NULL, 
	[Realligned_Tobacco_Flag] varchar(2) NOT NULL, 
	[CP_KEY_CATEGORY] varchar(41) NOT NULL, 
	[CP_KEY_PDM] varchar(41) NOT NULL
);