CREATE TABLE [dbo].[FOOD_DW_FCT_FOOD_SALES_BUDGET_V] (

	[CATEGORY_MANAGER_CODE] varchar(8) NULL, 
	[MSC_CATEGORY_CD] varchar(8) NULL, 
	[BRANCH_SK] bigint NULL, 
	[BRANCH_CODE] varchar(15) NULL, 
	[BRANCH_BUS_PILLAR_CODE] varchar(8) NULL, 
	[SOURCE_SYSTEM_CD] int NULL, 
	[INTERNAL_SALES_IND] varchar(10) NULL, 
	[FRESH_FLAG] varchar(15) NULL, 
	[TOBACCO_FLAG] varchar(15) NULL, 
	[BUDGET_PLAN_TYP] varchar(8) NULL, 
	[PRIVATELABEL_TYPE] varchar(50) NULL, 
	[FISC_WK_END_DT] int NULL, 
	[PDM_CODE] varchar(10) NULL, 
	[BUDGET_AMT] float NULL, 
	[REALLIGNED_CATEGORY_MANAGER_CD] varchar(8) NULL, 
	[REALLIGNED_TOBOCCO_FLAG] varchar(2) NOT NULL, 
	[CP_KEY_CATEGORY] varchar(41) NOT NULL, 
	[CP_KEY_MANAGER] varchar(33) NOT NULL, 
	[CP_KEY_PDM] varchar(43) NOT NULL, 
	[CP_KEY_PDM_MANAGER] varchar(35) NOT NULL
);