-- Sample configuration data for flat file ingestion testing - Universal schema (Warehouse version)
-- Using synthetic data generator parquet files

INSERT INTO config.config_flat_file_ingestion (
    config_id,
    config_name,
    source_file_path,
    source_file_format,
    target_workspace_id,
    target_datastore_id,
    target_datastore_type,
    target_schema_name,
    target_table_name,
    staging_table_name,
    file_delimiter,
    has_header,
    encoding,
    date_format,
    timestamp_format,
    schema_inference,
    -- Advanced CSV handling options
    quote_character,
    escape_character,
    multiline_values,
    ignore_leading_whitespace,
    ignore_trailing_whitespace,
    null_value,
    empty_value,
    comment_character,
    max_columns,
    max_chars_per_column,
    custom_schema_json,
    partition_columns,
    sort_columns,
    write_mode,
    merge_keys,
    data_validation_rules,
    error_handling_strategy,
    execution_group,
    active_yn,
    created_date,
    modified_date,
    created_by,
    modified_by,
    -- New fields for incremental synthetic data import support
    import_pattern,
    date_partition_format,
    table_relationship_group,
    batch_import_enabled,
    file_discovery_pattern,
    import_sequence_order,
    date_range_start,
    date_range_end,
    skip_existing_dates
) VALUES 
(
    'synthetic_customers_001',
    'Synthetic Data - Customers (Retail OLTP Small)',
    'Files/synthetic_data/parquet/single/retail_oltp_small/customers.parquet',
    'parquet',
    '{{varlib:config_workspace_id}}',
    '{{varlib:config_lakehouse_id}}',
    'lakehouse',
    'raw',
    'synthetic_customers',
    NULL,
    NULL,
    NULL,
    NULL,
    'yyyy-MM-dd',
    'yyyy-MM-dd HH:mm:ss',
    1,
    NULL,
    '',
    'customer_id',
    'overwrite',
    '',
    NULL,
    'fail',
    1,
    'Y',
    '2024-01-15',
    NULL,
    'system',
    NULL,
    -- New fields for incremental synthetic data import support
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'synthetic_products_002',
    'Synthetic Data - Products (Retail OLTP Small)',
    'Files/synthetic_data/parquet/single/retail_oltp_small/products.parquet',
    'parquet',
    '{{varlib:config_workspace_id}}',
    '{{varlib:config_lakehouse_id}}',
    'lakehouse',
    'raw',
    'synthetic_products',
    NULL,
    NULL,
    NULL,
    NULL,
    'yyyy-MM-dd',
    'yyyy-MM-dd HH:mm:ss',
    1,
    NULL,
    'category',
    'product_id',
    'overwrite',
    '',
    NULL,
    'log',
    1,
    'Y',
    '2024-01-15',
    NULL,
    'system',
    NULL,
    -- New fields for incremental synthetic data import support
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'synthetic_orders_003',
    'Synthetic Data - Orders (Retail OLTP Small)',
    'Files/synthetic_data/parquet/single/retail_oltp_small/orders.parquet',
    'parquet',
    '{{varlib:config_workspace_id}}',
    '{{varlib:config_lakehouse_id}}',
    'lakehouse',
    'raw',
    'synthetic_orders',
    NULL,
    NULL,
    NULL,
    NULL,
    'yyyy-MM-dd',
    'yyyy-MM-dd HH:mm:ss',
    1,
    NULL,
    '',
    'order_date',
    'overwrite',
    '',
    NULL,
    'fail',
    1,
    'Y',
    '2024-01-15',
    NULL,
    'system',
    NULL,
    -- New fields for incremental synthetic data import support
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'synthetic_order_items_004',
    'Synthetic Data - Order Items (Retail OLTP Small)',
    'Files/synthetic_data/parquet/single/retail_oltp_small/order_items.parquet',
    'parquet',
    '{{varlib:config_workspace_id}}',
    '{{varlib:config_lakehouse_id}}',
    'lakehouse',
    'raw',
    'synthetic_order_items',
    NULL,
    NULL,
    NULL,
    NULL,
    'yyyy-MM-dd',
    'yyyy-MM-dd HH:mm:ss',
    1,
    NULL,
    '',
    'order_id',
    'overwrite',
    '',
    NULL,
    'log',
    1,
    'Y',
    '2024-01-15',
    NULL,
    'system',
    NULL,
    -- New fields for incremental synthetic data import support
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'synthetic_customers_warehouse_001',
    'Synthetic Data - Customers (Warehouse)',
    'Files/synthetic_data/parquet/single/retail_oltp_small/customers.parquet',
    'parquet',
    '{{varlib:config_workspace_id}}',
    '{{varlib:config_wh_warehouse_id}}',
    'warehouse',
    'raw',
    'synthetic_customers',
    'staging_synthetic_customers',
    NULL,
    NULL,
    NULL,
    'yyyy-MM-dd',
    'yyyy-MM-dd HH:mm:ss',
    1,
    NULL,
    '',
    'customer_id',
    'overwrite',
    '',
    NULL,
    'fail',
    2,
    'Y',
    '2024-01-15',
    NULL,
    'system',
    NULL,
    -- New fields for incremental synthetic data import support
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'synthetic_products_warehouse_002',
    'Synthetic Data - Products (Warehouse)',
    'Files/synthetic_data/parquet/single/retail_oltp_small/products.parquet',
    'parquet',
    '{{varlib:config_workspace_id}}',
    '{{varlib:config_wh_warehouse_id}}',
    'warehouse',
    'raw',
    'synthetic_products',
    'staging_synthetic_products',
    NULL,
    NULL,
    NULL,
    'yyyy-MM-dd',
    'yyyy-MM-dd HH:mm:ss',
    1,
    NULL,
    '',
    'product_id',
    'overwrite',
    '',
    NULL,
    'log',
    2,
    'Y',
    '2024-01-15',
    NULL,
    'system',
    NULL,
    -- New fields for incremental synthetic data import support
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'synthetic_orders_warehouse_003',
    'Synthetic Data - Orders (Warehouse)',
    'Files/synthetic_data/parquet/single/retail_oltp_small/orders.parquet',
    'parquet',
    '{{varlib:config_workspace_id}}',
    '{{varlib:config_wh_warehouse_id}}',
    'warehouse',
    'raw',
    'synthetic_orders',
    'staging_synthetic_orders',
    NULL,
    NULL,
    NULL,
    'yyyy-MM-dd',
    'yyyy-MM-dd HH:mm:ss',
    1,
    NULL,
    '',
    'order_date',
    'overwrite',
    '',
    NULL,
    'fail',
    2,
    'Y',
    '2024-01-15',
    NULL,
    'system',
    NULL
);

-- Insert additional complex CSV configuration examples
INSERT INTO config.config_flat_file_ingestion (
    config_id, config_name, source_file_path, source_file_format,
    target_workspace_id, target_datastore_id, target_datastore_type,
    target_schema_name, target_table_name, staging_table_name,
    file_delimiter, has_header, encoding, date_format, timestamp_format, schema_inference,
    -- Advanced CSV handling options
    quote_character, escape_character, multiline_values, ignore_leading_whitespace, ignore_trailing_whitespace,
    null_value, empty_value, comment_character, max_columns, max_chars_per_column,
    custom_schema_json, partition_columns, sort_columns, write_mode, merge_keys,
    data_validation_rules, error_handling_strategy, execution_group, active_yn,
    created_date, modified_date, created_by, modified_by,
    -- New fields for incremental synthetic data import support
    import_pattern, date_partition_format, table_relationship_group,
    batch_import_enabled, file_discovery_pattern, import_sequence_order,
    date_range_start, date_range_end, skip_existing_dates
) VALUES 
(
    'complex_csv_warehouse_001',
    'Complex CSV - Customer Comments with Newlines (Warehouse)',
    'Files/sample_data/complex_customer_feedback.csv',
    'csv',
    '{{varlib:config_workspace_id}}',
    '{{varlib:config_wh_warehouse_id}}',
    'warehouse',
    'raw',
    'customer_feedback_complex',
    'staging_customer_feedback_complex',
    ',',
    1,
    'utf-8',
    'yyyy-MM-dd',
    'yyyy-MM-dd HH:mm:ss',
    1,
    -- Advanced CSV configuration for multiline and comments
    '"', '\', 1, 1, 1,
    'NULL', '', '#', 50, 10000,
    NULL, '', 'feedback_id', 'overwrite', '',
    NULL, 'fail', 5, 'N',
    '2024-01-15', NULL, 'system', NULL,
    -- New fields for incremental synthetic data import support
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
),
(
    'complex_csv_warehouse_002',
    'Complex CSV - Product Descriptions with Quotes (Warehouse)',
    'Files/sample_data/products_with_complex_descriptions.csv',
    'csv',
    '{{varlib:config_workspace_id}}',
    '{{varlib:config_wh_warehouse_id}}',
    'warehouse',
    'raw',
    'products_complex_descriptions',
    'staging_products_complex_descriptions',
    ',',
    1,
    'utf-8',
    'yyyy-MM-dd',
    'yyyy-MM-dd HH:mm:ss',
    1,
    -- Advanced CSV configuration for handling quotes and special characters
    '"', '"', 1, 0, 0,
    '', '', NULL, 100, 50000,
    NULL, 'category', 'product_id', 'merge', 'product_id',
    NULL, 'log', 5, 'N',
    '2024-01-15', NULL, 'system', NULL,
    -- New fields for incremental synthetic data import support
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
);

-- Insert incremental synthetic data import configurations
-- These demonstrate the new date-partitioned import capabilities
INSERT INTO config.config_flat_file_ingestion (
    config_id, config_name, source_file_path, source_file_format,
    target_workspace_id, target_datastore_id, target_datastore_type,
    target_schema_name, target_table_name, staging_table_name,
    file_delimiter, has_header, encoding, date_format, timestamp_format,
    schema_inference, custom_schema_json, partition_columns, sort_columns,
    write_mode, merge_keys, data_validation_rules, error_handling_strategy,
    execution_group, active_yn, created_date, created_by,
    quote_character, escape_character, multiline_values, ignore_leading_whitespace,
    ignore_trailing_whitespace, null_value, empty_value, comment_character,
    max_columns, max_chars_per_column,
    import_pattern, date_partition_format, table_relationship_group,
    batch_import_enabled, file_discovery_pattern, import_sequence_order,
    date_range_start, date_range_end, skip_existing_dates
) VALUES 
(
    'retail_customers_incremental_wh',
    'Retail Customers Incremental Import (Warehouse)',
    'Files/synthetic_data/csv/series/retail_oltp_small/nested/snapshot_customers',
    'csv',
    '{{varlib:config_workspace_id}}',
    '{{varlib:config_wh_warehouse_id}}',
    'warehouse',
    'bronze',
    'customers',
    'customers_staging',
    ',',
    1,
    'utf-8',
    'yyyy-MM-dd',
    'yyyy-MM-dd HH:mm:ss',
    1,
    NULL,
    'year_month',
    'customer_id',
    'merge',
    'customer_id',
    '{"required_columns": ["customer_id", "first_name", "last_name"]}',
    'log',
    10,
    'Y',
    GETDATE(),
    'admin',
    '"',
    '"',
    1,
    0,
    0,
    '',
    '',
    '#',
    100,
    50000,
    'date_partitioned',
    'YYYY/MM/DD',
    'retail_oltp',
    1,
    '**/customers/*.csv',
    1,
    '2024-01-01',
    '2024-01-30',
    1
),
(
    'retail_products_incremental_wh',
    'Retail Products Incremental Import (Warehouse)',
    'Files/synthetic_data/csv/series/retail_oltp_small/nested/snapshot_products',
    'csv',
    '{{varlib:config_workspace_id}}',
    '{{varlib:config_wh_warehouse_id}}',
    'warehouse',
    'bronze',
    'products',
    'products_staging',
    ',',
    1,
    'utf-8',
    'yyyy-MM-dd',
    'yyyy-MM-dd HH:mm:ss',
    1,
    NULL,
    'category',
    'product_id',
    'merge',
    'product_id',
    '{"required_columns": ["product_id", "product_name", "category"]}',
    'log',
    10,
    'Y',
    GETDATE(),
    'admin',
    '"',
    '"',
    1,
    0,
    0,
    '',
    '',
    '#',
    100,
    50000,
    'date_partitioned',
    'YYYY/MM/DD',
    'retail_oltp',
    1,
    '**/products/*.csv',
    2,
    '2024-01-01',
    '2024-01-30',
    1
),
(
    'retail_orders_incremental_wh',
    'Retail Orders Incremental Import (Warehouse)',
    'Files/synthetic_data/csv/series/retail_oltp_small/nested/orders',
    'csv',
    '{{varlib:config_workspace_id}}',
    '{{varlib:config_wh_warehouse_id}}',
    'warehouse',
    'bronze',
    'orders',
    'orders_staging',
    ',',
    1,
    'utf-8',
    'yyyy-MM-dd',
    'yyyy-MM-dd HH:mm:ss',
    1,
    NULL,
    'year_month',
    'order_id',
    'append',
    NULL,
    '{"required_columns": ["order_id", "customer_id", "order_date"]}',
    'log',
    11,
    'Y',
    GETDATE(),
    'admin',
    '"',
    '"',
    1,
    0,
    0,
    '',
    '',
    '#',
    100,
    50000,
    'date_partitioned',
    'YYYY/MM/DD',
    'retail_oltp',
    1,
    '**/orders/*.csv',
    4,
    '2024-01-01',
    '2024-01-30',
    0
),
(
    'retail_order_items_incremental_wh',
    'Retail Order Items Incremental Import (Warehouse)',
    'Files/synthetic_data/csv/series/retail_oltp_small/nested/order_items',
    'csv',
    '{{varlib:config_workspace_id}}',
    '{{varlib:config_wh_warehouse_id}}',
    'warehouse',
    'bronze',
    'order_items',
    'order_items_staging',
    ',',
    1,
    'utf-8',
    'yyyy-MM-dd',
    'yyyy-MM-dd HH:mm:ss',
    1,
    NULL,
    'year_month',
    'order_item_id',
    'append',
    NULL,
    '{"required_columns": ["order_item_id", "order_id", "product_id"]}',
    'log',
    11,
    'Y',
    GETDATE(),
    'admin',
    '"',
    '"',
    1,
    0,
    0,
    '',
    '',
    '#',
    100,
    50000,
    'date_partitioned',
    'YYYY/MM/DD',
    'retail_oltp',
    1,
    '**/order_items/*.csv',
    5,
    '2024-01-01',
    '2024-01-30',
    0
);

PRINT '✓ Inserted 13 sample configuration records (9 original + 4 incremental synthetic data)';
PRINT '✓ Includes incremental synthetic data import configurations demonstrating:';
PRINT '  - Snapshot tables (customers, products) with merge mode';
PRINT '  - Incremental tables (orders, order_items) with append mode';
PRINT '  - Date-partitioned processing with YYYY/MM/DD folder structure';
PRINT '  - All configurations use actual files from tmp/spark/Files/synthetic_data directory';