"""dbt profile for the native ``dbt-fabricspark`` adapter, generated from the value set.

One ``profiles.yml`` per dbt project, written into ``<dbt_project>/profiles/`` so it travels
with ``ingen_fab deploy upload-dbt-project`` and is picked up by the orchestrator notebook.
Nothing is written to ``~/.dbt``; the CLI proxy points ``--profiles-dir`` at the project.

The profile name comes from the project's ``dbt_project.yml`` (``profile:``). Each
environment of the value set becomes two targets:

- ``<env>``: for a developer machine or a CI runner, over the Fabric Livy API, authenticating
  with ``azure.identity.DefaultAzureCredential`` (Azure CLI login, service-principal
  environment variables, managed or workload identity, the same order as the rest of ingen_fab).
- ``<env>-notebook``: for the orchestrator notebook inside Fabric, authenticating with a
  token the notebook fetches in the kernel (``notebookutils.credentials.getToken("pbi")``)
  and passes to dbt through ``DBT_FABRIC_TOKEN``.

The default lakehouse of a target is, in order: the ``--lakehouse`` prefix given on the
command line, the ``dbt_default_lakehouse`` variable (a prefix such as ``lh_bronze`` or a
lakehouse name), or the only lakehouse the value set declares. With several lakehouses and
no choice, the command fails and lists the prefixes; nothing prompts, so CI never hangs.
Models write to other lakehouses through dbt's ``database`` config (schema-enabled
lakehouses), not through the profile.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Optional

import yaml

FABRIC_API_ENDPOINT = "https://api.fabric.microsoft.com/v1"
NOTEBOOK_TARGET_SUFFIX = "-notebook"
NOTEBOOK_TOKEN_ENV = "DBT_FABRIC_TOKEN"
PROFILES_DIRNAME = "profiles"
GENERATED_HEADER = (
    "# Generated by `ingen_fab dbt profile` from the project's Variable Library value sets.\n"
    "# Do not edit: change the value set (or dbt_default_lakehouse / dbt_schema /\n"
    "# dbt_threads) and run the command again.\n"
)


class ProfileError(ValueError):
    """The value set or the dbt project does not hold what a profile needs."""


@dataclass(frozen=True)
class LakehouseRef:
    prefix: str
    name: str
    lakehouse_id: str
    workspace_id: str


def read_profile_name(dbt_project_dir: Path) -> str:
    """The ``profile:`` of ``dbt_project.yml`` (closes the hardcoded-name issue, #23)."""
    project_file = Path(dbt_project_dir) / "dbt_project.yml"
    if not project_file.is_file():
        raise ProfileError(f"dbt project not found: {project_file}")
    data = yaml.safe_load(project_file.read_text(encoding="utf-8")) or {}
    name = data.get("profile")
    if not name or not isinstance(name, str):
        raise ProfileError(f"'profile' is not set in {project_file}")
    return name


def value_set_path(project_path: Path, environment: str) -> Path:
    return (
        Path(project_path)
        / "fabric_workspace_items"
        / "config"
        / "var_lib.VariableLibrary"
        / "valueSets"
        / f"{environment}.json"
    )


def list_environments(project_path: Path) -> list[str]:
    folder = value_set_path(project_path, "x").parent
    return sorted(p.stem for p in folder.glob("*.json")) if folder.is_dir() else []


def read_value_set(project_path: Path, environment: str) -> dict[str, str]:
    path = value_set_path(project_path, environment)
    if not path.is_file():
        available = ", ".join(list_environments(project_path)) or "none"
        raise ProfileError(f"value set not found: {path} (available: {available})")
    data = json.loads(path.read_text(encoding="utf-8"))
    return {
        v["name"]: v.get("value", "")
        for v in data.get("variableOverrides", [])
        if v.get("name")
    }


def _is_placeholder(value: str) -> bool:
    return not value or "REPLACE_WITH" in value


def discover_lakehouses(values: dict[str, str]) -> dict[str, LakehouseRef]:
    """Every ``<prefix>_lakehouse_id`` with a usable id and workspace id."""
    found: dict[str, LakehouseRef] = {}
    for key, lakehouse_id in values.items():
        if not key.endswith("_lakehouse_id"):
            continue
        prefix = key[: -len("_lakehouse_id")]
        workspace_id = values.get(f"{prefix}_workspace_id") or values.get(
            "fabric_deployment_workspace_id", ""
        )
        if _is_placeholder(lakehouse_id) or _is_placeholder(workspace_id):
            continue
        found[prefix] = LakehouseRef(
            prefix=prefix,
            name=values.get(f"{prefix}_lakehouse_name") or prefix,
            lakehouse_id=lakehouse_id,
            workspace_id=workspace_id,
        )
    return dict(sorted(found.items()))


def choose_default_lakehouse(
    values: dict[str, str],
    lakehouses: dict[str, LakehouseRef],
    requested: Optional[str] = None,
) -> LakehouseRef:
    """``requested`` or ``dbt_default_lakehouse`` (prefix or name), else the only one."""
    wanted = requested or values.get("dbt_default_lakehouse") or ""
    if wanted:
        for ref in lakehouses.values():
            if wanted in (ref.prefix, ref.name):
                return ref
        if f"{wanted}_lakehouse_id" in values:
            raise ProfileError(
                f"lakehouse '{wanted}' is declared but has no id yet; deploy it with "
                "AUTO_UPDATE_ITEM_IDS=true or run `ingen_fab init workspace`"
            )
        raise ProfileError(
            f"lakehouse '{wanted}' is not declared in the value set; "
            f"known prefixes: {', '.join(lakehouses) or 'none'}"
        )
    if len(lakehouses) == 1:
        return next(iter(lakehouses.values()))
    if not lakehouses:
        raise ProfileError(
            "no lakehouse with a real id in the value set; run `ingen_fab init workspace` "
            "or fill the <prefix>_lakehouse_id variables"
        )
    raise ProfileError(
        "several lakehouses declared; choose one with --lakehouse <prefix> or set "
        f"dbt_default_lakehouse in the value set (prefixes: {', '.join(lakehouses)})"
    )


def _flag(values: dict[str, str], key: str, default: bool) -> bool:
    raw = (values.get(key) or "").strip().lower()
    if not raw:
        return default
    if raw in ("true", "1", "yes", "y"):
        return True
    if raw in ("false", "0", "no", "n"):
        return False
    raise ProfileError(f"{key} must be true or false, got {raw!r}")


def _int(values: dict[str, str], key: str, default: int) -> int:
    raw = values.get(key)
    try:
        return int(raw) if raw not in (None, "") else default
    except ValueError as e:
        raise ProfileError(f"{key} must be an integer, got {raw!r}") from e


def session_name(profile_name: str, environment: str) -> str:
    """Name of the Spark session a dbt run opens, as listed in the Fabric Monitor hub. The
    notebook target passes ``<environment>-notebook`` so runs started inside Fabric can be told
    from runs started on a laptop or a CI runner."""
    return f"dbt-{profile_name}-{environment}"


def build_target(
    values: dict[str, str],
    lakehouse: LakehouseRef,
    *,
    profile_name: str,
    environment: str,
    notebook: bool,
) -> dict[str, Any]:
    """One dbt target for the native adapter.

    ``schema`` is the ``dbt_schema`` variable when set (``dbo`` for a schema-enabled
    lakehouse) and the lakehouse name otherwise: that is the adapter's own parse-time rule
    for telling the two lakehouse kinds apart.
    """
    target: dict[str, Any] = {
        "type": "fabricspark",
        "method": "livy",
        "endpoint": values.get("fabric_api_endpoint") or FABRIC_API_ENDPOINT,
        "workspaceid": lakehouse.workspace_id,
        "lakehouseid": lakehouse.lakehouse_id,
        "lakehouse": lakehouse.name,
        "schema": values.get("dbt_schema") or lakehouse.name,
        "threads": _int(values, "dbt_threads", 4),
        "connect_retries": 2,
        "connect_timeout": 30,
        # Off by default: with reuse on, the adapter leaves the Livy session running after dbt
        # exits (it expects a later run to pick it up), which costs capacity for nothing when
        # runs are minutes apart. Opt in per project with dbt_reuse_session=true.
        "reuse_session": _flag(values, "dbt_reuse_session", False),
        # The Spark (Livy) session of a dbt run shows under this name in the Fabric Monitor
        # hub: say what it is, for which profile and environment.
        "spark_config": {
            "name": session_name(
                profile_name, f"{environment}-notebook" if notebook else environment
            )
        },
    }
    if notebook:
        # Raw-token mode (the adapter calls it ``int_tests``): the orchestrator notebook
        # fetches the token in the kernel with notebookutils and passes it to the dbt child
        # process through this environment variable. ``fabric_notebook`` cannot be used
        # there: it imports notebookutils inside the child process, which only exists in
        # the kernel.
        target["authentication"] = "int_tests"
        target["accessToken"] = "{{ env_var('" + NOTEBOOK_TOKEN_ENV + "') }}"
    else:
        target["authentication"] = "token_credential"
        target["credential_class"] = "azure.identity.DefaultAzureCredential"
        target["credential_kwargs"] = {"exclude_interactive_browser_credential": True}
    return target


def build_profile(
    project_path: Path,
    dbt_project_dir: Path,
    environments: Iterable[str],
    *,
    default_environment: str,
    lakehouse: Optional[str] = None,
    skipped: Optional[dict[str, str]] = None,
) -> dict[str, Any]:
    """The whole ``profiles.yml`` content: one profile, two targets per environment.

    The default environment must resolve. Another environment whose value set cannot
    produce a target yet (placeholder ids, no default lakehouse) is left out and recorded in
    ``skipped`` (environment -> reason) when that dict is given; without it, it is an error.
    """
    profile_name = read_profile_name(dbt_project_dir)
    outputs: dict[str, Any] = {}
    for environment in environments:
        try:
            values = read_value_set(project_path, environment)
            ref = choose_default_lakehouse(
                values, discover_lakehouses(values), lakehouse
            )
        except ProfileError as e:
            if environment == default_environment or skipped is None:
                raise ProfileError(f"environment '{environment}': {e}") from e
            skipped[environment] = str(e)
            continue
        outputs[environment] = build_target(
            values,
            ref,
            profile_name=profile_name,
            environment=environment,
            notebook=False,
        )
        outputs[f"{environment}{NOTEBOOK_TARGET_SUFFIX}"] = build_target(
            values,
            ref,
            profile_name=profile_name,
            environment=environment,
            notebook=True,
        )
    if default_environment not in outputs:
        raise ProfileError(
            f"default environment '{default_environment}' is not among {list(environments)}"
        )
    return {profile_name: {"target": default_environment, "outputs": outputs}}


def profiles_dir(dbt_project_dir: Path) -> Path:
    return Path(dbt_project_dir) / PROFILES_DIRNAME


def write_profile(profile: dict[str, Any], dbt_project_dir: Path) -> Path:
    folder = profiles_dir(dbt_project_dir)
    folder.mkdir(parents=True, exist_ok=True)
    path = folder / "profiles.yml"
    path.write_text(
        GENERATED_HEADER
        + yaml.safe_dump(profile, sort_keys=False, default_flow_style=False),
        encoding="utf-8",
    )
    return path


def validate_with_adapter(profile: dict[str, Any]) -> None:
    """Let the installed adapter check every target the way it would at run time
    (required fields, GUID formats, endpoint, credential wiring). No network."""
    try:
        from dbt.adapters.fabricspark.credentials import FabricSparkCredentials
    except ImportError as e:
        raise ProfileError(
            "dbt-fabricspark is not installed in this environment; install the dbt "
            "dependency group (uv sync --group dbt)"
        ) from e

    for profile_name, body in profile.items():
        for target_name, target in body["outputs"].items():
            try:
                FabricSparkCredentials.from_dict(dict(target))
            except Exception as e:  # the adapter raises its own error types
                raise ProfileError(
                    f"target '{target_name}' of profile '{profile_name}' rejected by "
                    f"dbt-fabricspark: {e}"
                ) from e


def ensure_profile(
    project_path: Path,
    dbt_project: str,
    environment: str,
    *,
    lakehouse: Optional[str] = None,
    all_environments: bool = True,
    skipped: Optional[dict[str, str]] = None,
) -> Path:
    """Generate, validate and write the project's profile; return the profiles directory.

    Environments other than the current one that cannot produce a target yet are left out
    and reported in ``skipped`` (environment -> reason).
    """
    dbt_project_dir = Path(project_path) / dbt_project
    environments = (
        list_environments(project_path) if all_environments else [environment]
    )
    if environment not in environments:
        environments.append(environment)
    profile = build_profile(
        project_path,
        dbt_project_dir,
        environments,
        default_environment=environment,
        lakehouse=lakehouse,
        skipped=skipped if skipped is not None else {},
    )
    validate_with_adapter(profile)
    write_profile(profile, dbt_project_dir)
    return profiles_dir(dbt_project_dir)
